apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          # Adicionamos isto para todas as apps. Resolve o erro do chmod /data.
          volumeMounts:
            - name: data-storage
              mountPath: /data
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | default "production" | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      # Define o volume ao nível do Pod para todas as apps
      volumes:
        - name: data-storage
          emptyDir: {}