apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      # SEGURANÇA: Define o dono do volume para o utilizador 1000
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # SEGURANÇA: Força o container a correr como utilizador comum
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          # PERSISTÊNCIA: Monta sempre o /data para evitar erros de permissão
          volumeMounts:
            - name: storage-volume
              mountPath: {{ .Values.persistence.path }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | default "production" | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: storage-volume
          emptyDir: {}