namespace: default
app:
  name: app
replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 

persistence:
  enabled: false
  path: "/app/data" # Caminho padrão onde o volume será montado
  size: "1Gi"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: "production"

# Ingress e Probes (Garante que existem para o Helm não falhar)
ingress:
  enabled: true
  host: ""
livenessProbe:
  initialDelaySeconds: 60
readinessProbe:
  initialDelaySeconds: 60