namespace: default
app:
  name: app
replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 80 # Valor neutro, o Workflow mudará para 8000 ou 3000

persistence:
  enabled: true
  path: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: "production"