namespace: deisi

app:
  name: app

replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  name: app
  type: NodePort
  port: 80
  targetPort: 8000  # <--- Mudei para 8000 porque os teus logs mostram Django

resources:
  requests:
    memory: "256Mi"   
    cpu: "100m"      
  limits:
    memory: "512Mi"  
    cpu: "500m"

env:
  NODE_ENV: "production"