name: Central Deploy
on:
  workflow_call:
    inputs:
      targetPort:
        type: string
        default: "80"
      usePersistence:
        type: boolean
        default: true
    secrets:
      GHCR_TOKEN:
        required: true
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.repository.name }}
      BASE_DOMAIN: 134.122.74.17.nip.io
      FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Repo Meta (Topics)
        id: repo_meta
        uses: actions/github-script@v7
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput("topics", JSON.stringify(repo.topics || []));

      - name: Define Namespace
        run: |
          TOPICS='${{ steps.repo_meta.outputs.topics }}'
          if [[ "$TOPICS" == *"tfc"* ]]; then echo "NS=tfc" >> $GITHUB_ENV
          elif [[ "$TOPICS" == *"deisi"* ]]; then echo "NS=deisi" >> $GITHUB_ENV
          elif [[ "$TOPICS" == *"alunos"* ]]; then echo "NS=alunos" >> $GITHUB_ENV
          else exit 1; fi

      - name: Build & Push
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }}
          docker build -t $FULL_IMAGE_NAME:${{ github.sha }} .
          docker push $FULL_IMAGE_NAME:${{ github.sha }}

      - name: Deploy
        run: |
          mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          # Checkout do platform-ci para aceder ao Helm Chart
          actions/checkout@v4
          with:
            repository: deisi-apps-test-afonso-lucas-tfc/platform-ci
            path: platform
          
          helm upgrade --install $APP_NAME ./platform/helm/app -n $NS \
            --set app.name=$APP_NAME \
            --set service.targetPort=${{ inputs.targetPort }} \
            --set image.repository=$FULL_IMAGE_NAME \
            --set image.tag=${{ github.sha }} \
            --set ingress.host=$APP_NAME.$BASE_DOMAIN