name: Central Deploy

on:
  workflow_call:
    inputs:
      targetPort:
        description: 'Porta interna da aplicação'
        required: false
        type: string
        default: "8000"
      usePersistence:
        description: 'Ativar volume persistente'
        required: false
        type: boolean
        default: false
      mountPath:
        description: 'Caminho onde o volume será montado'
        required: false
        type: string
        default: "/data"
    secrets:
      GHCR_TOKEN:
        required: true
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.repository.name }}
      BASE_DOMAIN: 134.122.74.17.nip.io
      FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Ler topics do repositório
        id: repo_meta
        uses: actions/github-script@v7
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput("topics", JSON.stringify(repo.topics || []));

      - name: Definir namespace a partir dos topics
        run: |
          TOPICS='${{ steps.repo_meta.outputs.topics }}'
          if [[ "$TOPICS" == *"tfc"* ]]; then echo "NAMESPACE=tfc" >> $GITHUB_ENV
          elif [[ "$TOPICS" == *"deisi"* ]]; then echo "NAMESPACE=deisi" >> $GITHUB_ENV
          elif [[ "$TOPICS" == *"alunos"* ]]; then echo "NAMESPACE=alunos" >> $GITHUB_ENV
          else exit 1; fi

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build e Push
        run: |
          docker build -t $FULL_IMAGE_NAME:${{ github.sha }} .
          docker push $FULL_IMAGE_NAME:${{ github.sha }}

      - name: Configurar kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Checkout platform-ci repo
        uses: actions/checkout@v4
        with:
          repository: deisi-apps-test-afonso-lucas-tfc/platform-ci
          path: platform
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Deploy com Helm
        run: |
          helm upgrade --install $APP_NAME ./platform/helm/app -n $NAMESPACE \
            --create-namespace \
            --set namespace=$NAMESPACE \
            --set app.name=$APP_NAME \
            --set service.name=$APP_NAME \
            --set ingress.name=$APP_NAME \
            --set ingress.enabled=true \
            --set ingress.host=$INGRESS_HOST \
            --set image.repository=$FULL_IMAGE_NAME \
            --set image.tag=${{ github.sha }} \
            --set service.targetPort=${{ inputs.targetPort }} \
            --set persistence.enabled=${{ inputs.usePersistence }} \
            --set persistence.path=${{ inputs.mountPath }}